# Generated by Django 5.2.7 on 2025-10-12 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.designation'),
            preserve_default=False,
        ),
    ]
